# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vitor/Py-projects/autoCave/templates/AutoHeal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(354, 226)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.manacase_2 = QtWidgets.QSlider(Dialog)
        self.manacase_2.setMaximum(8)
        self.manacase_2.setSliderPosition(0)
        self.manacase_2.setOrientation(QtCore.Qt.Horizontal)
        self.manacase_2.setObjectName("manacase_2")
        self.gridLayout.addWidget(self.manacase_2, 4, 4, 1, 1)
        self.cb_heal = QtWidgets.QCheckBox(Dialog)
        self.cb_heal.setTristate(False)
        self.cb_heal.setObjectName("cb_heal")
        self.gridLayout.addWidget(self.cb_heal, 2, 1, 1, 1)
        self.tb_life3 = QtWidgets.QPushButton(Dialog)
        self.tb_life3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_life3.setObjectName("tb_life3")
        self.gridLayout.addWidget(self.tb_life3, 5, 2, 1, 1)
        self.manacase_3 = QtWidgets.QSlider(Dialog)
        self.manacase_3.setMaximum(8)
        self.manacase_3.setSliderPosition(0)
        self.manacase_3.setOrientation(QtCore.Qt.Horizontal)
        self.manacase_3.setObjectName("manacase_3")
        self.gridLayout.addWidget(self.manacase_3, 5, 4, 1, 1)
        self.cb_mana = QtWidgets.QCheckBox(Dialog)
        self.cb_mana.setObjectName("cb_mana")
        self.gridLayout.addWidget(self.cb_mana, 2, 4, 1, 1)
        self.lifecase_2 = QtWidgets.QSlider(Dialog)
        self.lifecase_2.setMaximum(8)
        self.lifecase_2.setOrientation(QtCore.Qt.Horizontal)
        self.lifecase_2.setObjectName("lifecase_2")
        self.gridLayout.addWidget(self.lifecase_2, 4, 0, 1, 2)
        self.lifecase_3 = QtWidgets.QSlider(Dialog)
        self.lifecase_3.setMaximum(8)
        self.lifecase_3.setOrientation(QtCore.Qt.Horizontal)
        self.lifecase_3.setObjectName("lifecase_3")
        self.gridLayout.addWidget(self.lifecase_3, 5, 0, 1, 2)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 3, 4, 1)
        self.tb_life1 = QtWidgets.QPushButton(Dialog)
        self.tb_life1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_life1.setAutoRepeatDelay(300)
        self.tb_life1.setObjectName("tb_life1")
        self.gridLayout.addWidget(self.tb_life1, 3, 2, 1, 1)
        self.tb_mana2 = QtWidgets.QPushButton(Dialog)
        self.tb_mana2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_mana2.setObjectName("tb_mana2")
        self.gridLayout.addWidget(self.tb_mana2, 4, 5, 1, 1)
        self.tb_mana3 = QtWidgets.QPushButton(Dialog)
        self.tb_mana3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_mana3.setObjectName("tb_mana3")
        self.gridLayout.addWidget(self.tb_mana3, 5, 5, 1, 1)
        self.tb_mana1 = QtWidgets.QPushButton(Dialog)
        self.tb_mana1.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_mana1.setObjectName("tb_mana1")
        self.gridLayout.addWidget(self.tb_mana1, 3, 5, 1, 1)
        self.manacase_1 = QtWidgets.QSlider(Dialog)
        self.manacase_1.setMaximum(8)
        self.manacase_1.setSliderPosition(0)
        self.manacase_1.setOrientation(QtCore.Qt.Horizontal)
        self.manacase_1.setObjectName("manacase_1")
        self.gridLayout.addWidget(self.manacase_1, 3, 4, 1, 1)
        self.tb_life2 = QtWidgets.QPushButton(Dialog)
        self.tb_life2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.tb_life2.setObjectName("tb_life2")
        self.gridLayout.addWidget(self.tb_life2, 4, 2, 1, 1)
        self.lifecase_1 = QtWidgets.QSlider(Dialog)
        self.lifecase_1.setStyleSheet("s")
        self.lifecase_1.setMaximum(8)
        self.lifecase_1.setSliderPosition(0)
        self.lifecase_1.setOrientation(QtCore.Qt.Horizontal)
        self.lifecase_1.setInvertedAppearance(False)
        self.lifecase_1.setInvertedControls(True)
        self.lifecase_1.setObjectName("lifecase_1")
        self.gridLayout.addWidget(self.lifecase_1, 3, 0, 1, 2)
        self.speed = QtWidgets.QDoubleSpinBox(Dialog)
        self.speed.setProperty("value", 1.0)
        self.speed.setObjectName("speed")
        self.gridLayout.addWidget(self.speed, 0, 3, 1, 3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.bt_region = QtWidgets.QPushButton(Dialog)
        self.bt_region.setMaximumSize(QtCore.QSize(70, 16777215))
        self.bt_region.setObjectName("bt_region")
        self.gridLayout.addWidget(self.bt_region, 0, 1, 1, 1)
        self.region_label = QtWidgets.QLabel(Dialog)
        self.region_label.setObjectName("region_label")
        self.gridLayout.addWidget(self.region_label, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cb_heal.setText(_translate("Dialog", "Auto Heal"))
        self.tb_life3.setText(_translate("Dialog", "F4"))
        self.cb_mana.setText(_translate("Dialog", "Auto Mana"))
        self.tb_life1.setText(_translate("Dialog", "F1"))
        self.tb_mana2.setText(_translate("Dialog", "F4"))
        self.tb_mana3.setText(_translate("Dialog", "F5"))
        self.tb_mana1.setText(_translate("Dialog", "F2"))
        self.tb_life2.setText(_translate("Dialog", "F3"))
        self.label.setText(_translate("Dialog", "Intervalo:"))
        self.bt_region.setText(_translate("Dialog", "REGION"))
        self.region_label.setText(_translate("Dialog", "<html><head/><body><p>X: 0  Y: 0</p><p>W: 0 H: 0</p></body></html>"))
import resources_rc
